<?php

namespace Database\Seeders;

use App\Models\PromoCode;
use Illuminate\Database\Seeder;

class PromoCodeSeeder extends Seeder
{
    public function run(): void
    {
        $samples = [
            [
                'code' => 'SAVE10',
                'title' => 'Save 10% sitewide',
                'description' => 'Limited public offer — 10% off your order.',
                'type' => 'percent',
                'value' => 10,
                'min_order_amount' => 0,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_PUBLIC,
                'usage_limit' => 500,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(3),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'BUNDLE20',
                'title' => 'Bundle boost',
                'description' => '20% off orders over $50 — or use volume discount at checkout (pick one).',
                'type' => 'percent',
                'value' => 20,
                'min_order_amount' => 50,
                'max_discount_amount' => 75,
                'audience' => PromoCode::AUDIENCE_PUBLIC,
                'usage_limit' => 200,
                'usage_count' => 0,
                'per_customer_limit' => 2,
                'starts_at' => now(),
                'expires_at' => now()->addDays(45),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'FREESHIP5',
                'title' => 'Five dollars off',
                'description' => 'Fixed $5 off any order $25+.',
                'type' => 'fixed',
                'value' => 5,
                'min_order_amount' => 25,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_PUBLIC,
                'usage_limit' => 100,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addDays(30),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'VIP15',
                'title' => 'VIP early access',
                'description' => 'Exclusive 15% for loyal customers (admin assigns email).',
                'type' => 'percent',
                'value' => 15,
                'min_order_amount' => 0,
                'max_discount_amount' => 100,
                'audience' => PromoCode::AUDIENCE_VIP,
                'usage_limit' => null,
                'usage_count' => 0,
                'per_customer_limit' => 3,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'is_active' => true,
                'show_on_promo_page' => false,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'FAVORITE5',
                'title' => 'Favorite picks — 5% off',
                'description' => 'Save 5% on items you love. One use per customer.',
                'type' => 'percent',
                'value' => 5,
                'min_order_amount' => 0,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_PUBLIC,
                'usage_limit' => 1000,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'CART5',
                'title' => 'Cart bonus — 5% off',
                'description' => 'Add to cart and get 5% off your order. New customers only.',
                'type' => 'percent',
                'value' => 5,
                'min_order_amount' => 0,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_WELCOME,
                'usage_limit' => null,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'FIRSTSALE',
                'title' => 'First sale — 12% off',
                'description' => 'Exclusive welcome discount for new subscribers and first-time buyers.',
                'type' => 'percent',
                'value' => 12,
                'min_order_amount' => 0,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_WELCOME,
                'usage_limit' => null,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(3),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'THANKYOU10',
                'title' => 'Thank you — 10% off',
                'description' => 'Thanks for your first order! Use this code on your next purchase.',
                'type' => 'percent',
                'value' => 10,
                'min_order_amount' => 0,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_THANK_YOU,
                'usage_limit' => null,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'SIGNUP10',
                'title' => 'Sign up — 10% off',
                'description' => 'Create an account and enjoy 10% off your first order.',
                'type' => 'percent',
                'value' => 10,
                'min_order_amount' => 0,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_WELCOME,
                'usage_limit' => null,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'is_active' => true,
                'show_on_promo_page' => true,
                'is_auto_generated' => false,
            ],
            [
                'code' => 'NEWSLETTER10',
                'title' => 'Newsletter — 10% off',
                'description' => 'Thanks for subscribing! Enjoy 10% off your next order.',
                'type' => 'percent',
                'value' => 10,
                'min_order_amount' => 0,
                'max_discount_amount' => null,
                'audience' => PromoCode::AUDIENCE_WELCOME,
                'usage_limit' => null,
                'usage_count' => 0,
                'per_customer_limit' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addDays(30),
                'is_active' => true,
                'show_on_promo_page' => false,
                'is_auto_generated' => false,
            ],
        ];

        foreach ($samples as $data) {
            PromoCode::updateOrCreate(
                ['code' => $data['code']],
                $data
            );
        }
    }
}
