<?php

return [
    'hero' => [
        'autoplay_ms' => 5000,
        'slides' => [
            [
                'url' => '',
                'category_keywords' => ['shirt', 'tee', 'apparel', 't-shirt', 'tshirt'],
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1400&q=80',
                'alt' => 'Custom T-Shirts',
                'eyebrow' => 'Gen AI · Print on demand',
                'title_html' => 'Custom<br>T-Shirts',
                'title_size' => 'text-3xl sm:text-4xl',
                'description' => 'Design streetwear that actually feels like you.',
                'button_label' => 'Shop Now',
                'overlay_from' => 'rgba(226, 21, 12, 0.55)',
                'overlay_to' => 'rgba(0, 83, 102, 0.75)',
                'desktop_col_span' => 2,
            ],
            [
                'url' => '',
                'category_keywords' => ['case', 'phone'],
                'image' => 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=900&q=80',
                'alt' => 'Phone Cases',
                'eyebrow' => '',
                'title_html' => 'Phone Cases',
                'title_size' => 'text-2xl sm:text-3xl',
                'description' => '',
                'button_label' => 'Shop Now',
                'overlay_from' => 'rgba(0, 83, 102, 0.5)',
                'overlay_to' => 'rgba(0, 61, 77, 0.8)',
                'desktop_col_span' => 1,
            ],
            [
                'url' => '',
                'category_keywords' => ['hat', 'cap', 'beanie'],
                'image' => 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80',
                'alt' => 'Custom Hats',
                'eyebrow' => '',
                'title_html' => 'Hats &amp; Caps',
                'title_size' => 'text-2xl sm:text-3xl',
                'description' => '',
                'button_label' => 'Shop Now',
                'overlay_from' => 'rgba(242, 101, 34, 0.45)',
                'overlay_to' => 'rgba(0, 83, 102, 0.85)',
                'desktop_col_span' => 1,
            ],
        ],
    ],

    'sections' => [
        'pick_a_gift' => [
            'enabled' => true,
            'background' => '#ffffff',
            'eyebrow' => 'Gift ideas',
            'title_html' => 'Pick a <span class="gradient-text">Gift</span>',
            'subtitle' => 'Browse curated collections for every occasion',
            'items' => [],
        ],
        'flash_sale' => [
            'enabled' => true,
            'background' => '#ffffff',
            'eyebrow' => 'Limited time',
            'title_html' => 'Flash <span class="gradient-text">Sale</span>',
            'subtitle' => 'Grab exclusive deals before they are gone',
        ],
        'top_picks' => [
            'enabled' => true,
            'background' => '#ffffff',
            'eyebrow' => 'Personalized',
            'title_html' => 'Top Picks <span class="gradient-text">For You</span>',
            'subtitle' => 'Curated from what’s trending and what fits your style',
            'banners' => [
                'featured' => [
                    'image' => '',
                    'url' => '',
                    'title' => 'Create Your Own',
                    'subtitle' => 'Design custom products with AI and print on demand',
                ],
                'promo' => [
                    'image' => '',
                    'url' => '',
                    'title' => 'Shop all collections',
                    'subtitle' => 'Curated designs for every occasion',
                    'tag' => '',
                ],
            ],
        ],
        'latest_collections' => [
            'enabled' => true,
            'background' => '#ffffff',
            'eyebrow' => 'Curated picks',
            'title_html' => 'Latest <span class="gradient-text">Collections</span>',
            'subtitle' => 'Discover our newest collections and trending designs',
        ],
        'new_products' => [
            'enabled' => true,
            'background' => '#ffffff',
            'eyebrow' => 'Just dropped',
            'title_html' => 'New <span class="gradient-text">Products</span>',
            'subtitle' => 'Fresh designs and latest additions to our catalog',
        ],
        'customize_hero' => [
            'enabled' => true,
            'background' => '#ffffff',
            'title' => 'Customize Products To Reflect Your Unique Taste And Personality',
            'shirt_image' => 'https://images.unsplash.com/photo-1583743084905-05922234025e?auto=format&fit=crop&w=640&q=80',
            'design_image' => 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=300&q=80',
            'upload_label' => 'Upload image',
            'upload_url' => '/create-your-own',
            'float_images' => [
                'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=200&q=80',
                'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80',
                'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=200&q=80',
                'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=200&q=80',
                'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=200&q=80',
                'https://images.unsplash.com/photo-1620799140408-edc289dcb063?auto=format&fit=crop&w=200&q=80',
                'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=200&q=80',
            ],
        ],
        'blog' => [
            'enabled' => true,
            'background' => '#ffffff',
            'eyebrow' => 'Inspiration',
            'title_html' => 'Latest <span class="gradient-text">Blog Posts</span>',
            'subtitle' => 'Design tips, trends, and creative inspiration',
        ],
        'recently_viewed' => [
            'enabled' => true,
            'background' => '#f9fafb',
            'eyebrow' => 'Continue browsing',
            'title_html' => 'Recently <span class="gradient-text">Viewed</span>',
            'subtitle' => "Pick up where you left off with products you've explored",
        ],
        'why_choose' => [
            'enabled' => true,
            'background' => '#f9fafb',
            'autoplay_ms' => 4500,
            'eyebrow' => 'Our promise',
            'title_html' => 'Why Choose <span class="gradient-text">Bluprinter</span>?',
            'subtitle' => 'Professional customization with cutting-edge technology and support you can count on',
            'features' => [
                [
                    'title' => 'Premium Quality',
                    'description' => 'Professional-grade materials and state-of-the-art printing technology',
                    'accent' => 'petrol',
                    'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>',
                ],
                [
                    'title' => 'Fast Delivery',
                    'description' => 'Quick turnaround times with express shipping options available',
                    'accent' => 'cta',
                    'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>',
                ],
                [
                    'title' => 'Fair Pricing',
                    'description' => 'Transparent pricing with no hidden fees and competitive rates',
                    'accent' => 'petrol',
                    'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1"/>',
                ],
                [
                    'title' => '24/7 Support',
                    'description' => 'Dedicated customer support team available around the clock',
                    'accent' => 'orange',
                    'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192L5.636 18.364M12 2.25a9.75 9.75 0 100 19.5 9.75 9.75 0 000-19.5z"/>',
                ],
            ],
        ],
    ],
];
