<?php

return [
    'default_print_area' => [
        'x' => 30,
        'y' => 22,
        'width' => 40,
        'height' => 42,
    ],
    'default_design_price' => 3.00,
    'default_ai_design_price' => 0,
    'default_upload_design_price' => 0,
    'ai' => [
        'base_url' => env('STUDIO_AI_BASE_URL', 'https://api.openai.com/v1'),
        'api_key' => env('STUDIO_AI_API_KEY', env('OPENAI_API_KEY')),
        'image_model' => env('STUDIO_AI_IMAGE_MODEL'),
        'chat_model' => env('STUDIO_AI_CHAT_MODEL'),
        'completion_model' => env('STUDIO_AI_COMPLETION_MODEL'),
        'completion_base_url' => env('STUDIO_AI_COMPLETION_BASE_URL'),
        'completion_api_key' => env('STUDIO_AI_COMPLETION_API_KEY'),
        'image_size' => env('STUDIO_AI_IMAGE_SIZE', '1024x1024'),
        'image_count' => (int) env('STUDIO_AI_IMAGE_COUNT', 2),
        'timeout' => (int) env('STUDIO_AI_TIMEOUT', 180),
    ],
    'inspiration_prompts' => [
        'Vintage camping t-shirt design, mountain, forest, river, campfire, retro color palette.',
        'Minimal line-art wolf howling at the moon, black ink on transparent background.',
        'Retro 70s sunset with palm trees, bold type GOOD VIBES, warm orange and teal.',
        'Japanese wave illustration, navy and white, clean graphic suitable for a chest print.',
        'Cute cottagecore mushrooms and wildflowers, soft earth tones, sticker style.',
    ],
    'tag_colors' => [
        '#005366',
        '#e2150c',
        '#f26522',
        '#2563eb',
        '#16a34a',
        '#d97706',
    ],
    'color_map' => [
        'black' => '#000000',
        'white' => '#ffffff',
        'red' => '#dc2626',
        'blue' => '#2563eb',
        'green' => '#16a34a',
        'yellow' => '#eab308',
        'purple' => '#9333ea',
        'pink' => '#ec4899',
        'orange' => '#ea580c',
        'brown' => '#a16207',
        'gray' => '#6b7280',
        'grey' => '#6b7280',
        'navy' => '#1e3a8a',
        'maroon' => '#991b1b',
        'teal' => '#0d9488',
        'lime' => '#65a30d',
        'cyan' => '#06b6d4',
        'indigo' => '#4f46e5',
        'violet' => '#8b5cf6',
        'rose' => '#f43f5e',
        'amber' => '#f59e0b',
        'emerald' => '#10b981',
        'sky' => '#0ea5e9',
        'fuchsia' => '#d946ef',
        'charcoal' => '#374151',
        'dark gray' => '#374151',
        'dark heather' => '#374151',
        'dark blue' => '#1e40af',
        'dark green' => '#166534',
        'dark red' => '#991b1b',
        'light gray' => '#9ca3af',
        'light blue' => '#93c5fd',
        'light green' => '#86efac',
        'light pink' => '#fbb6ce',
        'cream' => '#fef7cd',
        'gold' => '#fbbf24',
        'silver' => '#9ca3af',
        'olive' => '#65a30d',
        'khaki' => '#a3a3a3',
        'beige' => '#f5f5dc',
        'tan' => '#d2b48c',
        'mint' => '#a7f3d0',
        'lavender' => '#e9d5ff',
        'coral' => '#fda4af',
        'turquoise' => '#5eead4',
        'sport grey' => '#9ca3af',
        'royal blue' => '#1d4ed8',
        'sand' => '#fbbf24',
        'forest green' => '#166534',
        'military green' => '#365314',
        'ash grey' => '#6b7280',
        'natural' => '#fef3c7',
        'heather' => '#9ca3af',
        'cardinal' => '#991b1b',
        'irish green' => '#15803d',
    ],
];
